name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'main'

jobs:

  check-linting-and-type-error:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install python dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
        
      - name: Run black
        run: |
          pip install --upgrade pip
          pip install black==22.12
          black .

      - name: Run mypy
        run: |
          pip install --upgrade pip
          pip install mypy
          mypy --ignore-missing-imports --exclude '__init__.py' .

  check-unit-test:
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install python dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: 'linux/amd64'

      - name: Build Docker image
        run: |
          docker build -t demo-fastapi-app:latest .

      - name: Run unit test
        run: |
          set -o pipefail
          docker run --rm -v $(pwd):/app demo-fastapi-app:latest \
            python -m pytest luffy --junitxml=luffy-pytests.xml --cov-fail-under=75 --cov-report=term-missing --cov-branch --cov=luffy | tee ./luffy-pytest-coverage.txt

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: luffy-test-results
          path: |
            ./luffy-pytest*.*
  
  coverage-comment:
    runs-on: ubuntu-latest
    needs: [check-unit-test]
    steps:
      - name: Download all workrun artifacts
        uses: actions/download-artifact@v3

      - name: Pytest Coverage Comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          multiple-files: |
            LUFFY-PYTEST, ./LUFFY-PYTEST/luffy-pytest-coverage.txt, ./LUFFY-PYTEST/luffy-pytests.xml
