name: Build and push docker image to ECR
on:
  workflow_dispatch:
    inputs:
      account_id:
        description: Account ID
        required: true
        type: string
      redeploy:
        description: Redeploy
        required: false
        type: boolean
        default: false

env:
  IMAGE_TAG: latest
  DOCKER_IMAGE_NAME: student-api
  AWS_DEFAULT_REGION: us-west-2
  AWS_ACCOUNT_ID: ${{ inputs.account_id }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Development
    timeout-minutes: 10
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        id: configure-aws
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/aws-github-ci-role
          role-duration-seconds: 3600
          role-skip-session-tagging: true
          role-session-name: student-api-deployment

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platform: linux/amd64

      - name: Build Docker image
        run: |
          cd luffy/api/
          docker build -t ${{ env.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      - name: Push Docker image
        run: |
          aws ecr get-login-password --region ${{ env.AWS_DEFAULT_REGION }} | docker login --username AWS --password-stdin ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_DEFAULT_REGION }}.amazonaws.com
          docker tag ${{ env.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }} ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_DEFAULT_REGION }}.amazonaws.com/student-api-ecr-repo:latest
          docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_DEFAULT_REGION }}.amazonaws.com/student-api-ecr-repo:latest

      - name: Update ECS Service
        if: (inputs.redeploy == true)
        run: |
          aws ecs update-service --cluster StudentApiCluster --service StudentApiService --force-new-deployment --region ${{ env.AWS_DEFAULT_REGION }}
